/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PageMode } from "./components/appn-page/appn-page";
export { PageMode } from "./components/appn-page/appn-page";
export namespace Components {
    interface AppnFooter {
    }
    interface AppnHeader {
        "pageTitle"?: string;
    }
    interface AppnPage {
        "mode": PageMode;
        "open": boolean;
        "pageTitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAppnFooterElement extends Components.AppnFooter, HTMLStencilElement {
    }
    var HTMLAppnFooterElement: {
        prototype: HTMLAppnFooterElement;
        new (): HTMLAppnFooterElement;
    };
    interface HTMLAppnHeaderElement extends Components.AppnHeader, HTMLStencilElement {
    }
    var HTMLAppnHeaderElement: {
        prototype: HTMLAppnHeaderElement;
        new (): HTMLAppnHeaderElement;
    };
    interface HTMLAppnPageElement extends Components.AppnPage, HTMLStencilElement {
    }
    var HTMLAppnPageElement: {
        prototype: HTMLAppnPageElement;
        new (): HTMLAppnPageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "appn-footer": HTMLAppnFooterElement;
        "appn-header": HTMLAppnHeaderElement;
        "appn-page": HTMLAppnPageElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppnFooter {
    }
    interface AppnHeader {
        "pageTitle"?: string;
    }
    interface AppnPage {
        "mode"?: PageMode;
        "open"?: boolean;
        "pageTitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "appn-footer": AppnFooter;
        "appn-header": AppnHeader;
        "appn-page": AppnPage;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "appn-footer": LocalJSX.AppnFooter & JSXBase.HTMLAttributes<HTMLAppnFooterElement>;
            "appn-header": LocalJSX.AppnHeader & JSXBase.HTMLAttributes<HTMLAppnHeaderElement>;
            "appn-page": LocalJSX.AppnPage & JSXBase.HTMLAttributes<HTMLAppnPageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
